events/urls.py
from django.conf.urls.defaults import *
from django.views.generic.list_detail import object_list
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day

info_dict = {
    'queryset': Calendar.objects.all(),
}

urlpatterns = patterns('',

# urls for Calendars
url(r'^calendar/$',
    object_list,
    name="schedule",
    kwargs={'queryset':Calendar.objects.all(), 'template_name':'schedule/calendar_list.html'}),

url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.calendar_by_periods',
    name="year_calendar",
    kwargs={'periods': [Year], 'template_name': 'schedule/calendar_year.html'}),

url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.calendar_by_periods',
    name="tri_month_calendar",
    kwargs={'periods': [Month], 'template_name': 'schedule/calendar_tri_month.html'}),

url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.calendar_by_periods',
    name = "compact_calendar",
    kwargs={'periods': [Month], 'template_name': 'schedule/calendar_compact_month.html'}),

url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.calendar_by_periods',
    name = "month_calendar",
    kwargs={'periods': [Month], 'template_name': 'schedule/calendar_month.html'}),

url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.calendar_by_periods',
    name = "week_calendar",
    kwargs={'periods': [Week], 'template_name': 'schedule/calendar_week.html'}),

url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.calendar_by_periods',
    name = "day_calendar",
    kwargs={'periods': [Day], 'template_name': 'schedule/calendar_day.html'}),

url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.calendar',
    name = "calendar_home",
    ),

#Event Urls
url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
    'schedule.views.create_or_edit_event',
    name='calendar_create_event'),
url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
    'schedule.views.create_or_edit_event',
    name='edit_event'),
url(r'^event/(?P<event_id>\d+)/$',
    'schedule.views.event',
    name="event"), 
url(r'^event/delete/(?P<event_id>\d+)/$',
    'schedule.views.delete_event',
    name="delete_event"),

#urls for already persisted occurrences
url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
    'schedule.views.occurrence',
    name="occurrence"), 
url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
    'schedule.views.cancel_occurrence',
    name="cancel_occurrence"),
url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
    'schedule.views.edit_occurrence',
    name="edit_occurrence"),

#urls for unpersisted occurrences
url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
    'schedule.views.occurrence', 
    name="occurrence_by_date"),
url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
    'schedule.views.cancel_occurrence', 
    name="cancel_occurrence_by_date"),
url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
    'schedule.views.edit_occurrence', 
    name="edit_occurrence_by_date"),
    

#feed urls 
url(r'^feed/calendar/(.*)/$',
    'django.contrib.syndication.views.feed', 
    { "feed_dict": { "upcoming": UpcomingEventsFeed } }),
 
(r'^ical/calendar/(.*)/$', CalendarICalendar()),

 url(r'$', object_list, info_dict, name='schedule'), 
)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('' , views.index, name = 'index'),
	path('searchflight/', views.searchFlight, name='searchFlight'),
	path('<int:accommodation_id>/accommodation', views.detailAccommodation, name='detailPage'),
	path('<int:attraction_id>/attraction', views.detailAttraction, name='detailPage'),
]

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     path('<int:question_id>/results/', views.results, name='results'),
#     path('<int:question_id>/vote', views.vote, name = 'vote'),
# ]

homepage/pocketguide/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
]

pocketguide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
]

events/models/events.py
# -*- coding: utf-8 -*-
from django.contrib.contenttypes import fields
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.template.defaultfilters import date
from django.utils.translation import ugettext, ugettext_lazy as _
import datetime
from dateutil import rrule
from schedule.models.rules import Rule
from schedule.models.calendars import Calendar
from schedule.utils import OccurrenceReplacer

class EventManager(models.Manager):

    def get_for_object(self, content_object, distinction=None, inherit=True):
        return EventRelation.objects.get_events_for_object(content_object, distinction, inherit)

class Event(models.Model):
    '''
    This model stores meta data for a date.  You can relate this data to many
    other models.
    '''
    start = models.DateTimeField(_("start"))
    end = models.DateTimeField(_("end"),help_text=_("The end time must be later than the start time."))
    title = models.CharField(_("title"), max_length = 255)
    description = models.TextField(_("description"), null = True, blank = True)
    creator = models.ForeignKey(User, null = True, verbose_name=_("creator"))
    created_on = models.DateTimeField(_("created on"), default = datetime.datetime.now)
    rule = models.ForeignKey(Rule, null = True, blank = True, verbose_name=_("rule"), help_text=_("Select '----' for a one time only event."))
    end_recurring_period = models.DateTimeField(_("end recurring period"), null = True, blank = True, help_text=_("This date is ignored for one time only events."))
    calendar = models.ForeignKey(Calendar, blank=True)
    objects = EventManager()

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        app_label = 'schedule'

    def __unicode__(self):
        date_format = u'l, %s' % ugettext("DATE_FORMAT")
        return ugettext('%(title)s: %(start)s-%(end)s') % {
            'title': self.title,
            'start': date(self.start, date_format),
            'end': date(self.end, date_format),
        }

    def get_absolute_url(self):
        return reverse('event', args=[self.id])

    def create_relation(self, obj, distinction = None):
        """
        Creates a EventRelation between self and obj.
        """
        EventRelation.objects.create_relation(self, obj, distinction)

    def get_occurrences(self, start, end):
        """
        >>> rule = Rule(frequency = "MONTHLY", name = "Monthly")
        >>> rule.save()
        >>> event = Event(rule=rule, start=datetime.datetime(2008,1,1), end=datetime.datetime(2008,1,2))
        >>> event.rule
        <Rule: Monthly>
        >>> occurrences = event.get_occurrences(datetime.datetime(2008,1,24), datetime.datetime(2008,3,2))
        >>> ["%s to %s" %(o.start, o.end) for o in occurrences]
        ['2008-02-01 00:00:00 to 2008-02-02 00:00:00', '2008-03-01 00:00:00 to 2008-03-02 00:00:00']

        Ensure that if an event has no rule, that it appears only once.

        >>> event = Event(start=datetime.datetime(2008,1,1,8,0), end=datetime.datetime(2008,1,1,9,0))
        >>> occurrences = event.get_occurrences(datetime.datetime(2008,1,24), datetime.datetime(2008,3,2))
        >>> ["%s to %s" %(o.start, o.end) for o in occurrences]
        []

        """
        persisted_occurrences = self.occurrence_set.all()
        occ_replacer = OccurrenceReplacer(persisted_occurrences)
        occurrences = self._get_occurrence_list(start, end)
        final_occurrences = []
        for occ in occurrences:
            # replace occurrences with their persisted counterparts
            if occ_replacer.has_occurrence(occ):
                p_occ = occ_replacer.get_occurrence(
                        occ)
                # ...but only if they are within this period
                if p_occ.start < end and p_occ.end >= start:
                    final_occurrences.append(p_occ)
            else:
              final_occurrences.append(occ)
        # then add persisted occurrences which originated outside of this period but now
        # fall within it
        final_occurrences += occ_replacer.get_additional_occurrences(start, end)
        return final_occurrences

    def get_rrule_object(self):
        if self.rule is not None:
            params = self.rule.get_params()
            frequency = 'rrule.%s' % self.rule.frequency
            return rrule.rrule(eval(frequency), dtstart=self.start, **params)

    def _create_occurrence(self, start, end=None):
        if end is None:
            end = start + (self.end - self.start)
        return Occurrence(event=self,start=start,end=end, original_start=start, original_end=end)

    def get_occurrence(self, date):
        rule = self.get_rrule_object()
        if rule:
            next_occurrence = rule.after(date, inc=True)
        else:
            next_occurrence = self.start
        if next_occurrence == date:
            try:
                return Occurrence.objects.get(event = self, original_start = date)
            except Occurrence.DoesNotExist:
                return self._create_occurrence(next_occurrence)


    def _get_occurrence_list(self, start, end):
        """
        returns a list of occurrences for this event from start to end.
        """
        difference = (self.end - self.start)
        if self.rule is not None:
            occurrences = []
            if self.end_recurring_period and self.end_recurring_period < end:
                end = self.end_recurring_period
            rule = self.get_rrule_object()
            o_starts = rule.between(start-difference, end, inc=True)
            for o_start in o_starts:
                o_end = o_start + difference
                occurrences.append(self._create_occurrence(o_start, o_end))
            return occurrences
        else:
            # check if event is in the period
            if self.start < end and self.end >= start:
                return [self._create_occurrence(self.start)]
            else:
                return []

    def _occurrences_after_generator(self, after=None):
        """
        returns a generator that produces unpresisted occurrences after the
        datetime ``after``.
        """

        if after is None:
            after = datetime.datetime.now()
        rule = self.get_rrule_object()
        if rule is None:
            if self.end > after:
                yield self._create_occurrence(self.start, self.end)
            raise StopIteration
        date_iter = iter(rule)
        difference = self.end - self.start
        while True:
            o_start = date_iter.next()
            if o_start > self.end_recurring_period:
                raise StopIteration
            o_end = o_start + difference
            if o_end > after:
                yield self._create_occurrence(o_start, o_end)


    def occurrences_after(self, after=None):
        """
        returns a generator that produces occurrences after the datetime
        ``after``.  Includes all of the persisted Occurrences.
        """
        occ_replacer = OccurrenceReplacer(self.occurrence_set.all())
        generator = self._occurrences_after_generator(after)
        while True:
            next = generator.next()
            yield occ_replacer.get_occurrence(next)


class EventRelationManager(models.Manager):
    '''
    >>> EventRelation.objects.all().delete()
    >>> CalendarRelation.objects.all().delete()
    >>> data = {
    ...         'title': 'Test1',
    ...         'start': datetime.datetime(2008, 1, 1),
    ...         'end': datetime.datetime(2008, 1, 11)
    ...        }
    >>> Event.objects.all().delete()
    >>> event1 = Event(**data)
    >>> event1.save()
    >>> data['title'] = 'Test2'
    >>> event2 = Event(**data)
    >>> event2.save()
    >>> user1 = User(username='alice')
    >>> user1.save()
    >>> user2 = User(username='bob')
    >>> user2.save()
    >>> event1.create_relation(user1, 'owner')
    >>> event1.create_relation(user2, 'viewer')
    >>> event2.create_relation(user1, 'viewer')
    '''
    # Currently not supported
    # Multiple level reverse lookups of generic relations appears to be
    # unsupported in Django, which makes sense.
    #
    # def get_objects_for_event(self, event, model, distinction=None):
    #     '''
    #     returns a queryset full of instances of model, if it has an EventRelation
    #     with event, and distinction
    #     >>> event = Event.objects.get(title='Test1')
    #     >>> EventRelation.objects.get_objects_for_event(event, User, 'owner')
    #     [<User: alice>]
    #     >>> EventRelation.objects.get_objects_for_event(event, User)
    #     [<User: alice>, <User: bob>]
    #     '''
    #     if distinction:
    #         dist_q = Q(eventrelation__distinction = distinction)
    #     else:
    #         dist_q = Q()
    #     ct = ContentType.objects.get_for_model(model)
    #     return model.objects.filter(
    #         dist_q,
    #         eventrelation__content_type = ct,
    #         eventrelation__event = event
    #     )

    def get_events_for_object(self, content_object, distinction=None, inherit=True):
        '''
        returns a queryset full of events, that relate to the object through, the
        distinction

        If inherit is false it will not consider the calendars that the events
        belong to. If inherit is true it will inherit all of the relations and
        distinctions that any calendar that it belongs to has, as long as the
        relation has inheritable set to True.  (See Calendar)

        >>> event = Event.objects.get(title='Test1')
        >>> user = User.objects.get(username = 'alice')
        >>> EventRelation.objects.get_events_for_object(user, 'owner', inherit=False)
        [<Event: Test1: Tuesday, Jan. 1, 2008-Friday, Jan. 11, 2008>]

events/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from schedule.models import Event, Occurrence
import datetime
import time


class SpanForm(forms.ModelForm):

    start = forms.DateTimeField(widget=forms.SplitDateTimeWidget)
    end = forms.DateTimeField(widget=forms.SplitDateTimeWidget, help_text = _("The end time must be later than start time."))

    def clean_end(self):
        if self.cleaned_data['end'] <= self.cleaned_data['start']:
            raise forms.ValidationError(_("The end time must be later than start time."))
        return self.cleaned_data['end']


class EventForm(SpanForm):
    def __init__(self, hour24=False, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
    
    end_recurring_period = forms.DateTimeField(help_text = _("This date is ignored for one time only events."), required=False)
    
    class Meta:
        model = Event
        exclude = ('creator', 'created_on', 'calendar')
        

class OccurrenceForm(SpanForm):
    
    class Meta:
        model = Occurrence
        exclude = ('original_start', 'original_end', 'event', 'cancelled')

events/templates/schedule/_detail.html
{% load i18n %}
<div class="detail">
<h2 align="center">{{occurrence.title}}</h2>
<table align="center">
    <tr>
        <td class="left">Starts</td>
        <td>{% blocktrans with occurrence.start|date:_("DATETIME_FORMAT") as start_date %}{{ start_date }}{% endblocktrans %}</td>
    </tr>
    <tr>
        <td class="left">Ends</td>
        <td>{% blocktrans with occurrence.end|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
    </tr>
    {% if occurrence.event.rule %}
        {% if not occurrence.id %}
            <tr>
                <td class="left">Reoccurs</td><td>{{occurrence.event.rule}}</td>
            </tr>
            {% if occurrence.event.end_recurring_period %}
                <tr>
                    <td class="left">Until</td>
                    <td>{% blocktrans with occurrence.event.end_recurring_period|date:_("DATETIME_FORMAT") as end_date %}{{ end_date }}{% endblocktrans %}</td>
                </tr>
            {% endif %}
        {% endif %}
    {% endif %}
</table>
{% if occurrence.description %}
<h3>Description</h3>
<p>{{occurrence.description}}</p>
{% endif %}
</div>

events/templates/schedule/_dialogs.html
{% block extra_head %}
{{block.super}}
<script>
function openCancelDialog(node, cancel_url, delete_url, event){
  event.stopPropagation();
  var btns = {"This":function(){window.location=cancel_url;}, "All":function(){window.location=delete_url}, "Do nothing":function(){$(this).dialog("destroy");}};
  dia = $("#delete_dialog").dialog({'buttons':btns, 'modal':true});
  dia.dialog('open');
  return false;
}

function openEditDialog(node, occurrence_url, event_url, event){
  event.stopPropagation();
  var btns = {"This":function(){window.location=occurrence_url;}, "All":function(){window.location=event_url}, "Do nothing":function(){$(this).dialog("destroy");}};
  dia = $("#edit_dialog").dialog({'buttons':btns, 'modal':true});
  dia.dialog('open');
  return false;
}

function openDetail(node){
  var btns = { "Close":function(){$(this).dialog("destroy");}};
  dia = $($(node).attr("href")).dialog({'buttons':btns, 'modal':true, 'title':'Details'});
  dia.dialog('open');
  return false;
}

function openURL(url, event){
    event.stopPropagation();
    window.location=url;
}
</script>
{% endblock %}


<div style="display:none;" id="delete_dialog" title="Question">
  Do you want to cancel this occurrence or delete all occurrences of this event?
</div>

<div style="display:none;" id="edit_dialog" title="This is a recurring event">
  Do you want to edit this occurrence or all occurrences?
</div>

events/templates/schedule/_event_title.html
<span class="title">{{occurrence.title}}</span>

events/templates/schedule/_month_table.html
{% load scheduletags %}
<table align="center" class="calendar">
{% if day_names %}
<tr class="daysofweek">
<td>&nbsp;</td>
	{% for day_name in day_names %}<td{% ifnotequal size "small" %} width='120'{% endifnotequal %}>{{ day_name }}</td>
{% endfor %}
{% endif %}
{% for week in month.get_weeks %}
    <tr>
    <td>
        <a href="{% url week_calendar calendar.slug %}{% querystring_for_date week.start %}">
            {{week.start|date:"W"}}
        </a>
    </td>
    {% for day in week.get_days %}
	{% day_cell calendar day month size %}
    {% endfor %}
    </tr>
{% endfor %}
</table>

events/templates/schedule/_prevnext.html
{% load scheduletags %}
<div class="prevnext">
    <a href="{% prev_url target slug period %}">
      <img align="top" border="0" src="/site_media/schedule/img/left_mod.png"/>
    </a> 
    &nbsp; <b>{{period_name}}</b> &nbsp; 
    <a href="{% next_url target slug period %}">
      <img align="top" border="0" src="/site_media/schedule/img/right_mod.png"/>
    </a>
</div>

events/templates/schedule/calendar_day.html
{% extends "schedule/base.html" %}
{% load scheduletags %}


{% block body %}

{% include "schedule/_dialogs.html" %}
<div class="navigation">
  <a href="{% url week_calendar calendar.slug %}{% querystring_for_date periods.day.start 3 %}">
    Week
  </a>
  <a href="{% url month_calendar calendar.slug %}{% querystring_for_date periods.day.start 2 %}">
    Month
  </a>
  <a href="{% url year_calendar calendar.slug %}{% querystring_for_date periods.day.start 1%}">
    Year
  </a>
</div>
<div class="tablewrapper">
    <div class="calendarname">{{ calendar.name }}</div>
    {% prevnext "day_calendar" calendar.slug periods.day "l, F d, Y" %}
    <div class="now">
      <a href="{% url day_calendar calendar.slug %}">
        Today
      </a>
    </div>
</div>
<div style="position:absolute;">
    <div style="position:absolute;left:100px;">
      {% daily_table periods.day 420 120 600 0 12 %}
    </div>

    <div style="position:absolute;left:600px;">
      {% daily_table periods.day 420 120 600 12 24 %}
    </div>
</div>

{% endblock %}

events/templates/schedule/calendar_month.html
{% extends "schedule/base.html" %}
{% load scheduletags %}

 {% block body %}
{% include "schedule/_dialogs.html" %}
<div class="tablewrapper">
  <div class="calendarname">{{ calendar.name }}</div>
  {% prevnext "month_calendar" calendar.slug periods.month "F Y"%}
  <div class="now">
    <a href="{% url month_calendar calendar.slug %}">
      This month
    </a>
  </div>
  {% month_table calendar periods.month "regular" %}
</div>
<div class="navigation">
  <a href="{% url tri_month_calendar calendar.slug %}{% querystring_for_date periods.month.start 2 %}">
    Three Month Calendar
  </a>
  <a href="{% url year_calendar calendar.slug %}{% querystring_for_date periods.month.start 1%}">
    Full Year Calendar
  </a>
</div>
{% endblock %}

events/templates/schedule/calendar_week.html
{% extends "schedule/base.html" %}
{% load scheduletags %}

{% block body %}

{% include "schedule/_dialogs.html" %}

<div class="navigation">
  <a href="{% url month_calendar calendar.slug %}{% querystring_for_date periods.week.start 2 %}">
    Month
  </a>
  <a href="{% url year_calendar calendar.slug %}{% querystring_for_date periods.week.start 1%}">
    Year
  </a>
</div>

<div class="tablewrapper">
    <div class="calendarname">{{ calendar.name }}</div>
    {% prevnext "week_calendar" calendar.slug periods.week "\Week W, M Y" %}
    <div class="now">
      <a href="{% url week_calendar calendar.slug %}">
        This week
      </a>
    </div>
</div>

<div id="week">
  {% for day in periods.week.get_days %}
    <div class="weekday weekday{{forloop.counter}}">
      <div class="weekdayheader">
        <a href="{% url day_calendar calendar.slug %}{% querystring_for_date day.start %}">
          {{day.start|date:"l, d"}}
        </a>
      </div>
      <div class="weekdaytable">
      {% if forloop.first %}
          {% daily_table day 230 80 600 9 21 %}
      {% else %}
          {% daily_table day 150 15 600 9 21 %}
      {% endif %}
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

events/templates/schedule/calendar_year.html
{% extends "schedule/base.html" %}
{% load scheduletags %}
{% block body %}
<div class="tablewrapper">
    <div class="calendarname">{{ calendar.name }}</div>
    {% prevnext "year_calendar" calendar.slug periods.year "Y" %}
    <table align="center">
    <tr>
    {% for month in periods.year.get_months %}
        <td valign="top">
        <a href="{% url month_calendar calendar.slug %}{% querystring_for_date month.start 2 %}">
            {{month.name}}
        </a>
        {% month_table calendar month "small" %}</td>
        <td width="12">&nbsp;</td>
        {% ifequal forloop.counter 3  %}
            </tr>
            <tr>
        {% endifequal %}
        {% ifequal forloop.counter 6  %}
            </tr>
            <tr>
        {% endifequal %}
        {% ifequal forloop.counter  9 %}
            </tr>
            <tr>
        {% endifequal %}
    {% endfor %}
    </tr>
</table></p>
<div class="navigation">
  <a href="{% url month_calendar calendar.slug %}">
    Current Month Calendar
  </a>
  <a href="{% url year_calendar calendar.slug %}">
    Current Year Calendar
  </a>
</div>
{% endblock %}

events/templates/schedule/cancel_occurrence.html
{% extends "schedule/base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans "Delete" %}</h1>
{% trans "Are you sure that you really want to cancel this occurrence?" %}

<form action="." method="POST">
    <h2>{{ occurrence.title }}</h2>
    <strong>From</strong> {{ occurrence.start|date:_("DATETIME_FORMAT") }}
    <strong>to</strong> {{ occurrence.end|date:_("DATETIME_FORMAT") }} <br/>
    <input type="submit" value="{% trans "Delete" %}" name="submit" />
    <input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
    <input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

events/templates/schedule/create_event.html
{% extends "schedule/event_form_base.html" %}
{% load i18n %}

{% block body %}
<b>{% trans "Create or change event. All fields are required." %}</b>
<br/><br/>
<form action="" method="post">
<table>
{{ form.as_table }}
</table>
<br/>
<input type="submit" value="{% trans "Save" %}">
<input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
<input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

events/templates/schedule/delete_event.html
{% extends "schedule/base.html" %}
{% load i18n %}

{% block body %}
<h1>{% trans "Delete" %}</h1>
{% trans "Are you sure that you really want to delete it?" %}

<form action="." method="POST">
    {{ object }} <br/>
    <input type="submit" value="{% trans "Delete" %}" />
    <input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>

    <input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

events/templates/schedule/edit_occurrence.html
{% extends "schedule/event_form_base.html" %}
{% load i18n %}

{% block body %}
<b>{% trans "Create or change occurrence. All fields are required." %}</b>
<br/><br/>
<form action="" method="post">
<table>
{{ form.as_table }}
</table>
<br/>
<input type="submit" value="{% trans "Save" %}">
<input type="button" value="{% trans "Cancel" %}" onclick="window.location='{{next}}'"/>
<input type="hidden" name="next" value="{{next|default:""}}"/>
</form>
{% endblock %}

events/templates/schedule/event_form_base.html
{% extends "schedule/base.html" %}

{% block extra_head %}
    {{ block.super }}
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.timePicker.js"></script>
    <script type="text/javascript">
    $(function() {
        $("#id_start_0").datepicker({dateFormat: $.datepicker.ATOM});
        $("#id_end_0").datepicker({dateFormat: $.datepicker.ATOM});
        $("#id_start_1").timePicker();
        $("#id_end_1").timePicker();
        $("#id_end_recurring_period").datepicker({dateFormat: $.datepicker.ATOM});
        var oldTime = $.timePicker("#id_start_1").getTime();
        $("#id_start_1").change(function() {
          if ($("#id_end_1").val()) { // Only update when second input has a value.
          // Calculate duration.
          var duration = ($.timePicker("#id_end_1").getTime() - oldTime);
          var time = $.timePicker("#id_start_1").getTime();
          // Calculate and update the time in the second input.
          $.timePicker("#id_end_1").setTime(new Date(new Date(time.getTime() + duration)));
          oldTime = time;
          }
        });
        // Validate.
        // TODO this should validate date AND time
        $("#id_end_1").change(function() {
          if($.timePicker("#id_start_1").getTime() > $.timePicker(this).getTime()) {
          $(this).addClass("error");
          }
          else {
          $(this).removeClass("error");
          }
        });
    });
    </script>
{% endblock %}